# Generated by Django 2.1.7 on 2019-04-02 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='name',
        ),
        migrations.AddField(
            model_name='farmer',
            name='District',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='community_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='crop_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farm_area',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='instructor_possibility',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='language',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='marriage_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='parish',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='past_harvest',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='farmer',
            name='sub_county',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='village',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='Distict',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='login_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='sub_county',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='username',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='area',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='fartilizer1_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='fertilizer1_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='fertilizer2_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='fertilizer2_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='harvest_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='harvest_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='levelling',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='photo1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='report',
            name='photo2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='report',
            name='photo3',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='report',
            name='photo4',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='report',
            name='planting_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='rice_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='season',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sowing_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sowing_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='total_weedtimes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='watercourse_state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='weed_condition',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='harvest',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='season',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='season',
            name='username',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
