# Generated by Django 2.1.7 on 2019-04-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20190402_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='parish',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
