# Generated by Django 2.1.7 on 2019-04-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_officer_parish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officer',
            old_name='Distict',
            new_name='District',
        ),
    ]
