# Generated by Django 2.1.7 on 2019-04-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_auto_20190402_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='fartilizer1_type',
            new_name='fertilizer1_type',
        ),
    ]
